services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mgnlfeatures'
      - 'POSTGRES_PASSWORD=//db_password'
      - 'POSTGRES_USER=//db_username'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
